server {
    listen 80;
    
    # 나중에 도메인을 구매하시면 여기에 도메인을 적어주세요. (예: server_name seicompany.com;)
    server_name setrading.co.kr www.setrading.co.kr; 

    location / {
        # docker-compose에서 설정할 Next.js 컨테이너의 이름(sei-next)으로 라우팅
        proxy_pass http://sei-next:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # 클라이언트 실제 IP 전달
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}